export const BUILD = 'build'
export const ESM = 'esm'
export const CJS = 'cjs'
export const LIB = 'lib'
export const UMD = 'umd'
export const LESS_TO_CSS = 'lessToCss'
export const COPY_LESS = 'copyLess'
